# This is an OpenAPI Specification (https://swagger.io/specification/)
# for the multicast-notification-service owned by NHS Digital (https://digital.nhs.uk/)
openapi: '3.0.0'
info:
  title: 'Multicast Notification Service (MNS) - REST API'
  version: 'Computed and injected at build time by `scripts/set_version.py`'
  description: |
    ## Overview
    Before learning about the MNS API, we would recommend reviewing MNS as a service on the [MNS Service Page](https://digital.nhs.uk/services/multicast-notification-service).

    ![MNS High-level Diagram](assets/images/MNSOverview2.svg)

    This page is about how to implement the API for the Multicast Notificaton Service, to find out more about this service itself and its uses visit our [Multicast Notification Service](https://digital.nhs.uk/services/multicast-notification-service) service page.

    Use this API to publish or and subscribe to healthcare-related events. This API is currently only live with patient-related event. However, it is intended as a robust service that could support many types of future event e.g. changes related to healthcare organisations or staff.

    The events do not contain clinical information; they simply describe what type of event occurred to whom/what and where. A pointer is provided for retrieval of the data that the event refers to.

    This API is for systems that need to share healthcare information with other systems that need to stay up to date with changes to that information.

    You can:
      - Publish events.
      - Subscribe to events based on event type and optional corresponding criteria filter.

    Available and in development events can be viewed by visiting the [Multicast Notification Service Events Catalogue](https://digital.nhs.uk/developer/api-catalogue/multicast-notification-service/multicast-notification-service-events-catalogue).

    Data flow:
      1. An event occurs on an event publishers system. They publish the event to MNS, including a pointer to be used for retrieval of the event details.
      2. MNS matches the event to the subscription criteria of subscribing organisations and delivers it to their specified destinations, for example an AWS SQS queue.
      3. Subscribers retrieve details of the event from the pointer provided in the event.

    ## Who can use this API
    This API can be used by developers of services supporting the delivery of health and social care.

    Make sure you have a valid use case before you go too far with your development.

    You must do this before you can go live (see [Onboarding](#overview--onboarding) below).

    ## Related APIs
    The following API also provides access to healthcare-related events:
      - [National Events Management Service - FHIR API](https://digital.nhs.uk/developer/api-catalogue/national-events-management-service-fhir "National
      Events Management Service - FHIR API") - the predecessor to MNS, the difference is that the payloads MNS delivers are lightweight events that do not contain any clinical information, they signal that a state has changed and allow subscribers to retrieve up to date information from the authoritative source.
      - [Messaging Exchange for Social care and Health (MESH)](https://digital.nhs.uk/services/message-exchange-for-social-care-and-health-mesh) - available delivery system for receiving events from MNS.

    ## API status and roadmap
    This API is [in production (beta)](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#statuses).

    ## Service level
    This API is a bronze service, meaning it is operational and supported only during business hours (8am to 6pm), Monday to Friday excluding bank holidays.

    For more details, see [service levels](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#service-levels).
    ## Technology
    This API is a [REST-based](https://digital.nhs.uk/developer/guides-and-documentation/our-api-technologies#basic-rest) [publish-subscribe](https://digital.nhs.uk/developer/guides-and-documentation/introduction-to-healthcare-technology/integration-and-apis#publish-subscribe-events) API.

    The publish event structure is based on the recommendations of the [Cloud Events specification.](https://cloudevents.io/)

    Events received conform to the FHIR global standard for health care data exchange, specifically to FHIR R4 (v4.0.1).

    ## Network access
    This API is available on the internet.

    For more details see [Network access for APIs](https://digital.nhs.uk/developer/guides-and-documentation/network-access-for-apis).

    ## Security and authorisation

    This API has one access mode:
    - application-restricted access

    ### Application-restricted access
    Use this access mode if you need to publish an event from your system.

    This access mode is [application-restricted](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#application-restricted-apis), meaning we authenticate the calling application but not the end user.

    The end user could be:
    * a healthcare worker - for example they record an event in an application and that application then publishes to MNS
    * a patient - for example they make a change to their record in a patient-facing application and that application then publishes to MNS
    * not present at all - for example as part of a back end process where events from an NHS England product or system are generated

    In the above cases you must ensure the users are authenticated and suitably authorised locally

    To use this access mode, use the following security pattern:
    * [Application-restricted RESTful API - signed JWT authentication](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/application-restricted-restful-apis-signed-jwt-authentication)

    ## Environments and testing

    | Environment       | Base URL                                                               |
    | ----------------- | ---------------------------------------------------------------------- |
    | Sandbox           | `https://sandbox.api.service.nhs.uk/multicast-notification-service`    |
    | Integration test  | `https://int.api.service.nhs.uk/multicast-notification-service`        |
    | Production        | `https://api.service.nhs.uk/multicast-notification-service`            |

    ### Sandbox testing
    Our [sandbox environment](https://digital.nhs.uk/developer/guides-and-documentation/testing#sandbox-testing):
    * is for early developer testing
    * only covers a limited set of scenarios
    * is stateless, so does not actually persist any updates
    * is open access, so does not allow you to test authorisation

    For details of sandbox test scenarios, or to try out the sandbox using our 'Try this API' feature, see the documentation for each endpoint.

    Alternatively, you can try out the sandbox using our Postman collection (simply download the file from the link and import it into Postman):


    [![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/54527860-f64d9e7d-6095-46c3-bc58-92672de294f6)
    ## Onboarding
    During the planned private beta this service will only be available to NHS England product teams. The onboarding process is in development and we will be
    improving it iteratively as we gather feedback from the first set of users.

    ## Events
    Each event has its own documentation, which can be viewed by visiting the [Multicast Notification Service Events Catalogue](https://digital.nhs.uk/developer/api-catalogue/multicast-notification-service/multicast-notification-service-events-catalogue).

    ## Errors
    We use standard HTTP status codes to show whether an API request succeeded or not. They are usually in the range:

    * 200 to 299 if it succeeded, including code 202 if it was accepted by an API that needs to wait for further action
    * 400 to 499 if it failed because of a client error by your application
    * 500 to 599 if it failed because of an error on our server

    Errors specific to each API are shown in the Endpoints section, under Response. See our [reference guide](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#http-status-codes) for more on errors.

    ## Open source
    You might find the following [open source](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#open-source) resources useful:

    | Resource                  | Description                                                          | Links                                                                       |
    |---------------------------|----------------------------------------------------------------------|-----------------------------------------------------------------------------|
    | MNS API                   | Source code for the API proxy, sandbox and specification.            | [GitHub repo](https://github.com/NHSDigital/multicast-notification-service) |
    | FHIR libraries and SDKs   | Various open source libraries for integrating with FHIR APIs.        | [FHIR libraries and SDKs](https://digital.nhs.uk/developer/guides-and-documentation/api-technologies-at-nhs-digital#fhir-libraries-and-sdks) |

    We currently don't have any open source client libraries or sample code and the source code for the MNS backend is not currently in the open. If you think this would be useful, [contact us](https://digital.nhs.uk/developer/help-and-support).

    ## Contact us
    For help connecting to any NHS APIs see [Help and support building healthcare software](https://digital.nhs.uk/developer/help-and-support)

    For support with connecting to the MNS API [join our developer community](https://developer.community.nhs.uk/c/multicast-notification-service/57).


  contact:
    name: 'multicast-notification-service API Support'
    url: 'https://digital.nhs.uk/developer/help-and-support'
    email: api.management@nhs.net
security: []
servers:
  - url: 'https://sandbox.api.service.nhs.uk/multicast-notification-service'
    description: Sandbox environment.
  - url: 'https://int.api.service.nhs.uk/multicast-notification-service'
    description: Integration test environment.
  - url: 'https://api.service.nhs.uk/multicast-notification-service'
    description: Production environment.

tags:
  - name: events
    description: Event publishing
  - name: subscriptions
    description: Subscription management

paths:

  /events:

    post:
      summary: "Publish an event"
      tags:
        - events
      description: |
        ### Overview
        Use this endpoint to publish a healthcare-related event.

        The event contains only a minimum dataset based on the recommendations of the [CloudEvents specification](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md).

        ### Content-Type
        The Content-Type header for this endpoint is used to determine validation on the event body and should be set to `application/cloudevents+json` unless the event is a legacy event where it should be `application/json`.

        ### Data and Metadata:
          - Metadata: In the context of an event, metadata refers to the additional information that describes the event and provides context about it. For example, for [PDS](https://digital.nhs.uk/services/personal-demographics-service) events it includes elements such as the family name and date of birth which are primarily for verification. Users must be cautious not to use such metadata to modify a patient's demographic details. Instead, if updates are necessary, users should conduct a full PDS retrieval to ensure accuracy and completeness in their workflows.
          - Data: The inclusion of the data field might vary. Its presence is subject to agreements between the MNS team and the originating system. While the structure of the data might differ across various systems and scenarios, it's a general preference to have a pointer included. This pointer aids subscribers in accessing the entire record when necessary for their workflow.

        ### Sandbox testing
        You can test the following scenarios in our sandbox environment:

        | Scenario                           | Request                                                                    | Response                                                       |
        | ---------------------------------- | -------------------------------------------------------------------------- | -------------------------------------------------------------- |
        | Publish an event                   | Content-Type: `application/cloudevents+json` Event Type: `example-event-1` | HTTP Status 200 and response containing id and success status. |
        | Publish an event with invalid data | E.g. an event with an invalid value for `time`                             | HTTP Status 400 and response containing a validation error.    |

        You can try out the sandbox using the 'Try this API' feature on this page.
      operationId: publish-event
      parameters:
        - $ref: "parameters/headers/authorization.yaml"
        - $ref: "parameters/headers/x-correlation-id.yaml"
      requestBody:
        description: The cloudevent+json formatted body representing the event.
        required: true
        content:
          application/cloudevents+json:
            schema:
              $ref: "#/components/schemas/cloudevent"
            examples:
              imms-vaccination-record-change-1:
                description: "Create an immunisation vaccination record change event"
                value:
                  specversion: '1.0'
                  id: e0b3d12f-c64d-4b29-b23b-4a670941f572
                  source: uk.nhs.vaccinations-data-flow-management
                  type: imms-vaccination-record-change-1
                  time: '2020-06-01T13:00:00Z'
                  dataref: https://api.service.nhs.uk/immunisation-fhir-api/FHIR/R4/Immunization/29dc4e84-7e72-11ee-b962-0242ac120002
                  subject: '9912003888'
                  filtering:
                    generalpractitioner: 'FY4563'
                    sourceorganisation: 'FT6786'
                    sourceapplication: 'RAVS'
                    subjectage: 17
                    immunisationtype: 'HPV'
                    action: 'CREATE'
              nhshco-hc-complete-1:
                description: "Create a health check complete event"
                value:
                  specversion: '1.0'
                  id: 501c6aea-aff2-4431-b98e-1bf59192b045
                  source: uk.nhs.nhs-health-check-online
                  type: nhshco-hc-complete-1
                  time: '2020-06-01T13:00:00Z'
                  dataref: https://api.service.nhs.uk/patient-data-manager/FHIR/R4/Composition/b0b97bff-e3d7-4744-a09a-e55781886dd0/$document
                  subject: '9730676240'
                  filtering:
                    gppractice: 'XY11'
              vrs-proxy-role-deleted-1:
                description: "Create a proxy role deleted event"
                value:
                  specversion: '1.0'
                  id: 898cc706-9156-4d67-941a-b37ca9a85861
                  source: uk.nhs.validated-relationships-service
                  type: vrs-proxy-role-deleted-1
                  time: '2020-06-01T13:00:00Z'
                  dataref: https://api.service.nhs.uk/validated-relationships/FHIR/R4/Consent/ecc32c41
                  subject: '9730676240'
                  filtering:
                    patient_ods_code: 'M7Z0J'
                    proxy_ods_code: 'M7Z0J'
              vrs-proxy-role-changed-1:
                description: "Create a proxy role changed event"
                value:
                  specversion: '1.0'
                  id: 501c6aea-aff2-4431-b98e-1bf59192b045
                  source: uk.nhs.validated-relationships-service
                  type: vrs-proxy-role-changed-1
                  time: '2020-06-01T13:00:00Z'
                  dataref: https://api.service.nhs.uk/validated-relationships/FHIR/R4/Consent/ecc32c41
                  subject: '9730676240'
                  filtering:
                    patient_ods_code: 'M7Z0J'
                    proxy_ods_code: 'M7Z0J'
              vrs-proxy-role-created-1:
                description: "Create a proxy role created event"
                value:
                  specversion: '1.0'
                  id: 501c6aea-aff2-4431-b98e-1bf59192b045
                  source: uk.nhs.validated-relationships-service
                  type: vrs-proxy-role-created-1
                  time: '2020-06-01T13:00:00Z'
                  dataref: https://api.service.nhs.uk/validated-relationships/FHIR/R4/Consent/ecc32c41
                  subject: '9730676240'
                  filtering:
                    patient_ods_code: 'M7Z0J'
                    proxy_ods_code: 'M7Z0J'
              pds-record-change-2:
                description: "Create a PDS record change event"
                value:
                  specversion: '1.0'
                  id: 963b28e0-067a-4a3f-bee8-f613c23541b2
                  source: https://fhir.nhs.uk/Id/nhsSpineASID/477121000324
                  type: pds-record-change-2
                  time: '2020-06-01T13:00:00Z'
                  subject: '9912003888'
                  versionid: 'W/"16"'
                  filtering:
                    changed_name: true
                    registeredgpodscode: 'XY11'
                    nhsnumber: '9912003888'
              pds-death-notification-2:
                description: "Create a patient death status event"
                value:
                  specversion: '1.0'
                  id: 963b28e0-067a-4a3f-bee8-f613c23541b2
                  source: https://fhir.nhs.uk/Id/nhsSpineASID/477121000324
                  type: pds-death-notification-2
                  time: '2020-06-01T13:00:00Z'
                  dataref: https://api.service.nhs.uk/personal-demographics/FHIR/R4/Patient/9912003888
                  subject: '9912003888'
              pds-change-of-gp-2:
                description: "Create a change of gp event"
                value:
                  specversion: '1.0'
                  id: 56e9d7db-d70a-48bf-95f8-e779a741382a
                  source: https://fhir.nhs.uk/Id/nhsSpineASID/477121000324
                  type: pds-change-of-gp-2
                  time: '2020-06-01T13:00:00Z'
                  dataref: https://api.service.nhs.uk/personal-demographics/FHIR/R4/Patient/9912003888
                  subject: '9912003888'
              nhs-number-change-2:
                description: "Create a nhs number change event"
                value:
                  specversion: '1.0'
                  id: 685aec28-70bb-4763-853b-2bdc07a44415
                  source: https://fhir.nhs.uk/Id/nhsSpineASID/477121000324
                  type: nhs-number-change-2
                  time: '2020-06-01T13:00:00Z'
                  dataref: https://api.service.nhs.uk/personal-demographics/FHIR/R4/Patient/9912003888
                  subject: '9912003888'
              gpreg-change-gp-req-1:
                description: "Create a GP Registration Change event"
                value:
                  specversion: '1.0'
                  id: 236a1d4a-5d69-4fa9-9c7f-e72bf505aa5b
                  source: uk.nhs.register-with-a-gp-surgery-service
                  type: gpreg-change-gp-req-1
                  time: '2020-06-01T13:00:00Z'
                  dataref: https://api.service.nhs.uk/register-with-a-gp-surgery/applications/236a1d4a-5d69-4fa9-9c7f-e72bf505aa5b
                  subject: '9912003888'
                  filtering:
                    registrationencountercode: '3'
                    generalpractitioner: 'XY11'
              patientflags-change-1:
                description: "Create a Patient Flags Change event"
                value:
                  specversion: '1.0'
                  id: 16dbfb42-b5c0-4831-8258-f1a4d2491748
                  source: uk.nhs.patient-flags-service
                  type: patientflags-change-1
                  time: '2020-06-01T13:00:00Z'
                  dataref: https://api.service.nhs.uk/patient-flags-api/PatientFlag?patient=9912003888&code=NRAF
                  subject: '9912003888'
                  filtering:
                    flagtype: 'NRAF'
                    generalpractitioner: 'XY11'
                    origin: 'pfapi-internal-mns-int'
              pathology-laboratory-reporting-test-result-stored-1:
                description: "Create a pathology test result stored event"
                value:
                  specversion: '1.0'
                  id: 236a1d4a-5d69-4fa9-9c7f-e72bf505aa5b
                  source: uk.nhs.pathology-laboratory-reporting
                  type: pathology-laboratory-reporting-test-result-stored-1
                  time: '2020-06-01T13:00:00Z'
                  dataref: https://api.service.nhs.uk/patient-data-manager/FHIR/R4/Bundle/b0b97bff-e3d7-4744-a09a-e55781886dd0
                  subject: '9912003888'
                  filtering:
                    requestingOrganisationODS: 'A12345'
          application/json:
            schema:
              type: "object"
              required:
                - "id"
                - "type"
                - "subject"
                - "source"
                - "time"
              properties:
                id:
                  type: "string"
                  description: "Publishers must ensure that the id is unique within their system to ensure that when the MNS team trace messages, they can be certain that source + id will be unique. UUIDv4 format is expected."
                  example: "236a1d4a-5d69-4fa9-9c7f-e72bf505aa5b"
                type:
                  type: "string"
                  description: "A unique string representing the event type."
                  example: "pds-change-of-gp-1"
                subject:
                  $ref: "schemas/cloudevents/eventSubjectPatientExample.yaml"
                source:
                  type: "object"
                  required:
                    - "name"
                    - "identifier"
                  description: "Organisation responsible for publishing the event."
                  properties:
                    name:
                      type: "string"
                      description: "Organisation name"
                    identifier:
                      type: "object"
                      required:
                        - "system"
                        - "value"
                      description: "Must follow this identifier system: https://fhir.nhs.uk/Id/nhsSpineASID and provide the ASID Code as the value."
                      properties:
                        system:
                          type: "string"
                        value:
                          type: "string"
                  example:
                    name: "NHS Digital"
                    identifier:
                      system: "https://fhir.nhs.uk/Id/nhsSpineASID"
                      value: "477121000324"
                time:
                  type: "string"
                  format: "date-time"
                  description: "The time at which the event is published. This must be a compliant RFC3339 datetime in line with the FHIR standard for [system instants](https://hl7.org/fhir/R4/datatypes.html#instant). This means it can have seconds or milliseconds precision."
                  example: "2022-04-05T17:31:00.000Z"
                data:
                  type: object
                  description: "This field is optional, dependent on the agreements between the publishing system and the MNS team. While the data schema might vary based on the system and use-case, it is preferred to include a pointer for subscribers to access the full record when necessary for their workflow."
                  oneOf:
                    - $ref: "schemas/cloudevents/pdsChangeOfGpEventData.yaml"
                    - $ref: "schemas/cloudevents/pdsDeathEventData.yaml"
                    - $ref: "schemas/cloudevents/nhsNumberChangeEventData.yaml"
                  example:
                    versionId: 'W/"2"'
                    fullUrl: "https://int.api.service.nhs.uk/personal-demographics/FHIR/R4/Patient/9912003888"
                    registrationEncounterCode: "3"
                    provenance:
                      name: "The GP Practice"
                      identifier:
                        system: "https://fhir.nhs.uk/Id/nhsSpineASID"
                        value: "477121000323"
            examples:
              pdsChangeOfGpEvent:
                description: "(Version 1 Deprecated) Create a change of gp event"
                value:
                  id: 56e9d7db-d70a-48bf-95f8-e779a741382a
                  type: "pds-change-of-gp-1"
                  subject:
                    nhsNumber: "9912003888"
                    familyName: "DAWKINS"
                    dob: "2017-10-02"
                  source:
                    name: "NHS Digital"
                    identifier:
                      system: "https://fhir.nhs.uk/Id/nhsSpineASID"
                      value: "477121000324"
                  time: "2022-04-05T17:31:00.000Z"
                  data:
                    versionId: 'W/"2"'
                    fullUrl: "https://int.api.service.nhs.uk/personal-demographics/FHIR/R4/Patient/9912003888"
                    registrationEncounterCode: "3"
                    provenance:
                      name: "The GP Practice"
                      identifier:
                        system: "https://fhir.nhs.uk/Id/nhsSpineASID"
                        value: "477121000323"
              pdsDeathEvent:
                description: "(Version 1 Deprecated) Create a patient death status event"
                value:
                  id: 963b28e0-067a-4a3f-bee8-f613c23541b2
                  type: "pds-death-notification-1"
                  subject:
                    dob: "2017-10-02"
                    familyName: "DAWKINS"
                    nhsNumber: "9912003888"
                  source:
                    name: "NHS DIGITAL"
                    identifier:
                      system: "https://fhir.nhs.uk/Id/nhsSpineASID"
                      value: "477121000324"
                  time: "2022-04-05T17:31:00.000Z"
                  data:
                    versionId: 'W/"16"'
                    fullUrl: "https://int.api.service.nhs.uk/personal-demographics/FHIR/R4/Patient/9912003888"
                    deathNotificationStatus: "2"
                    provenance:
                      name: "The GP Practice"
                      identifier:
                        system: "https://fhir.nhs.uk/Id/nhsSpineASID"
                        value: "477121000323"
              nhsNumberChangeEvent:
                description: "(Version 1 Deprecated) Create a nhs number change event"
                value:
                  id: 685aec28-70bb-4763-853b-2bdc07a44415
                  type: "nhs-number-change-1"
                  subject:
                    dob: "2017-10-02"
                    familyName: "DAWKINS"
                    nhsNumber: "9912003888"
                  source:
                    name: "NHS DIGITAL"
                    identifier:
                      system: "https://fhir.nhs.uk/Id/nhsSpineASID"
                      value: "477121000324"
                  time: "2022-04-05T17:31:00.000Z"
                  data:
                    versionId: 'W/"16"'
                    fullUrl: "https://int.api.service.nhs.uk/personal-demographics/FHIR/R4/Patient/9912003888"
                    nhsNumberStatus: "I"
                    provenance:
                      name: "The GP Practice"
                      identifier:
                        system: "https://fhir.nhs.uk/Id/nhsSpineASID"
                        value: "477121000323"
      responses:
        "200":
          description: Success - the event is accepted and will be multicast to subscribers
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The id provided in the user's payload
                    example: "236a1d4a-5d69-4fa9-9c7f-e72bf505aa5b"
        "400":
          description: Invalid user input
          content:
            application/json:
              schema:
                type: object
                properties:
                  validationErrors:
                    type: object
                    description: Object containing the different errors on a per key basis
                    properties:
                      type:
                        type: string
                        example: Please provide a valid event type
        "401":
          $ref: "responses/401-unauthenticated.yaml"
        "403":
          description: "Unauthorized error"
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string
                    description: Error string that explains the problem
                    example: User is not authorized to handle the requested event type
        "500":
          $ref: "responses/500-internal-server-error.yaml"

  /subscriptions:

    post:
      summary: "Subscribe to events"
      tags:
        - subscriptions
      description: |
        ### Overview
        Use this endpoint to subscribe to healthcare-related events. You can view details of the available events on the [Multicast Notification Service Events Catalogue](https://digital.nhs.uk/developer/api-catalogue/multicast-notification-service/multicast-notification-service-events-catalogue).

        ### Subscription filtering
        You can filter the events you want to receive using the `criteria` field in the payload. As a minimum, you must specify the event type. For example, if you provide `eventType=gpreg-change-gp-req-1`
        this will mean that you receive all Validated GP Registration Request events. Depending on the event, additional filters are available, for example you can filter by `generalpractitioner`,`registrationencountercode` or `generalpractitioner_manufacturer_org` for `gpreg-change-gp-req-1` event.
        We are working with publishers and subscribers during private beta to identify any other useful filters for existing and future event types.

        For further information refer to the payload schema below.

        ### Subscription delivery
        You can specify the endpoint you want events delivered to using the `channel.endpoint` field in the payload. MNS currently only supports delivery to [AWS SQS](https://aws.amazon.com/sqs/) endpoints and
        [MESH](https://digital.nhs.uk/services/message-exchange-for-social-care-and-health-mesh) mailboxes. We are working with users during private beta to identify other potential delivery endpoints.
        There may be further delivery endpoints available in future.

        You can make suggestions using [feature upvote](https://nhs-digital-api-management.featureupvote.com).

        #### SQS Delivery
        Before events can be delivered to your SQS queue, you will need to complete some configuration steps during onboarding e.g. policy and encryption setup. When you make a create subscription request, you must provide your
        full SQS ARN.

        #### MESH Delivery
        If you have already completed [MESH onboarding](https://digital.nhs.uk/developer/api-catalogue/message-exchange-for-social-care-and-health-api#overview--end-to-end-process-to-integrate-with-mesh-api)
        then no further steps will be required aside from calling the subscriptions API. Use a MESH mailbox from their 'Path to Live integration' environment for all non-production MNS environments and a production mailbox for production MNS.

        The mailbox ID and workflow ID you require are supplied to the `channel.endpoint` field in a `mesh://` URL scheme.

        e.g. `mesh://MYMAILBOXOT101?workflow_id=myWorkflow101` specifies the mailbox ID `MYMAILBOXOT101` and the workflow ID `myWorkflow101`.

        ### Sandbox testing
        You can test the following scenarios in our sandbox environment:

        | Scenario                                 | Request                                                                  | Response                                                                    |
        | ---------------------------------------- | ------------------------------------------------------------------------ | --------------------------------------------------------------------------- |
        | Subscribe to an event                    | Content-Type: `application/fhir+json`                                    | HTTP Status 201 and response containing the id of the subscription created. |
        | Publish a subscription with invalid data | E.g. modify the subscription to have an invalid value for `resourceType` | HTTP Status 400 and response containing a validation error.                 |

        You can try out the sandbox using the 'Try this API' feature on this page.
      operationId: create-subscription
      parameters:
        - $ref: "parameters/headers/authorization.yaml"
        - $ref: "parameters/headers/x-correlation-id.yaml"
      requestBody:
        $ref: "requestBody/create-or-update-subscription-body.yaml"
      responses:
        "201":
          description: Created - the subscription has been successfully created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The subscription UUID created by the system
                    example: "236a1d4a-5d69-4fa9-9c7f-e72bf505aa5b"
        "400":
          description: Invalid user input
          content:
            application/json:
              schema:
                type: object
                properties:
                  validationErrors:
                    type: object
                    description: Object containing the different errors on a per key basis
                    properties:
                      resourceType:
                        type: string
                        example: Please provide the correct resource type for this endpoint
        "401":
          $ref: "responses/401-unauthenticated.yaml"
        "403":
          $ref: "responses/403-unauthorised.yaml"
        "409":
          $ref: "responses/409-matching-subscription.yaml"
        "500":
          $ref: "responses/500-internal-server-error.yaml"

    get:
      summary: "Get all subscriptions"
      tags:
        - subscriptions
      description: |
        ### Overview
        Use this endpoint to retrieve a list of all subscriptions belonging to you.
        If your application does not own any subscriptions, then this endpoint will return an empty list.
        The list of subscriptions is presented in a FHIR resource bundle, allowing pagination.

        ### Sandbox testing
        You can test the following scenarios in our sandbox environment:

        | Scenario                         | Request       | Response                                                    |
        | -------------------------------- | ------------- | ----------------------------------------------------------- |
        | User has a list of subscriptions | `GET` request | HTTP Status 200 containing a list of subscription resources |

        You can try out the sandbox using the 'Try this API' feature on this page.
      operationId: get-all-subscriptions
      parameters:
        - $ref: "parameters/headers/authorization.yaml"
        - $ref: "parameters/headers/x-correlation-id.yaml"
        - $ref: "parameters/query/continue_from.yaml"
      responses:
        "200":
          description: Successfully retrieved list of subscriptions
          content:
            application/fhir+json:
              schema:
                type: object
                properties:
                  resourceType:
                    type: string
                    enum: [Bundle]
                    example: Bundle
                  type:
                    type: string
                    enum: [searchset]
                    example: searchset
                  link:
                    type: array
                    items:
                      type: object
                      properties:
                        relation:
                          type: string
                          description: Relation type, e.g., 'self', 'next'. The 'next' relation is present only if there's additional content to paginate through.
                        url:
                          type: string
                          description: The URL for the relation. For 'next', this URL points to the next page of results.
                    example:
                      - relation: next
                        url: '/subscriptions?continue_from=ZmRqa2xmZGprc2xmamtsZHNqZmxkc2Zkcw=='
                  entry:
                    type: array
                    items:
                      $ref: "schemas/fhir/R4/Subscription.yaml"
                    example:
                      - channel:
                          endpoint: arn:aws:sqs:eu-west-2:123456789012:test-queue
                          payload: application/json
                          type: message
                        criteria: eventType=mns-test-signal-1
                        end: '2024-01-25T00:00:00.000Z'
                        id: 0e381025-985f-4696-a460-6c375b76e4d0
                        reason: ''
                        resourceType: Subscription
                        status: active
              example:
                resourceType: Bundle
                type: searchset
                link:
                  - relation: self
                    url: "/subscriptions"
                entry:
                  - channel:
                      endpoint: arn:aws:sqs:eu-west-2:123456789012:test-queue
                      payload: application/json
                      type: message
                    criteria: eventType=mns-test-signal-1
                    end: '2024-01-25T00:00:00.000Z'
                    id: 0e381025-985f-4696-a460-6c375b76e4d0
                    reason: ''
                    resourceType: Subscription
                    status: active
        "400":
          description: Invalid user input
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string
                    description: Error string that explains the problem
                    example: The continue_from field was not valid
        "401":
          $ref: "responses/401-unauthenticated.yaml"
        "403":
          $ref: "responses/403-unauthorised.yaml"
        "500":
          $ref: "responses/500-internal-server-error.yaml"

  /subscriptions/{id}:

    get:
      summary: "Get subscription details"
      tags:
        - subscriptions
      description: |
        ### Overview
        Use this endpoint to retrieve details of a subscription belonging to you.

        ### Sandbox testing
        You can test the following scenarios in our sandbox environment:

        | Scenario                                  | Request                                                                  | Response                                                                    |
        | ----------------------------------------- | ------------------------------------------------------------------------ | --------------------------------------------------------------------------- |
        | Subscription exists and can be retrieved  | `id=e9050741-ae87-4720-beb1-2abd9248e227`                                | HTTP Status 200 containing subscription details                             |
        | Subscription does not exist               | `id=236a1d4a-5d69-4fa9-9c7f-e72bf505aa5b` (or any other valid UUID)      | HTTP Status 404 containing problem description                              |

        You can try out the sandbox using the 'Try this API' feature on this page.
      operationId: get-subscription-by-id
      parameters:
        - $ref: "parameters/headers/authorization.yaml"
        - $ref: "parameters/headers/x-correlation-id.yaml"
        - $ref: "parameters/path/id.yaml"
      responses:
        "200":
          description: Successfully got subscription details
          content:
            application/fhir+json:
              schema:
                $ref: "schemas/fhir/R4/Subscription.yaml"
              example:
                id: "e9050741-ae87-4720-beb1-2abd9248e227"
                resourceType: "Subscription"
                status: "active"
                end: "2022-04-05T17:31:00.000Z"
                reason: "Business case A"
                criteria: "eventType=pds-change-of-gp-2"
                channel:
                  type: "message"
                  endpoint: "arn:aws:sqs:eu-west-2:123456789012:queue1"
                  payload: "application/json"
        "400":
          $ref: "responses/400-subscription-id.yaml"
        "401":
          $ref: "responses/401-unauthenticated.yaml"
        "403":
          $ref: "responses/403-unauthorised.yaml"
        "404":
          $ref: "responses/404-not-found.yaml"
        "500":
          $ref: "responses/500-internal-server-error.yaml"

    delete:
      summary: "Delete a subscription"
      tags:
        - subscriptions
      description: |
        ### Overview
        Use this endpoint to delete a subscription that you need to remove.

        ### Sandbox testing
        You can test the following scenarios in our sandbox environment:

        | Scenario                                  | Request                                                                  | Response                                                                    |
        | ----------------------------------------- | ------------------------------------------------------------------------ | --------------------------------------------------------------------------- |
        | Subscription exists and can be deleted    | `id=e9050741-ae87-4720-beb1-2abd9248e227`                                | HTTP Status 204 resource deleted response                                    |
        | Subscription does not exist               | `id=236a1d4a-5d69-4fa9-9c7f-e72bf505aa5b` (or any other valid UUID)      | HTTP Status 404 containing problem description                              |

        You can try out the sandbox using the 'Try this API' feature on this page.
      operationId: delete-subscription
      parameters:
        - $ref: "parameters/headers/authorization.yaml"
        - $ref: "parameters/headers/x-correlation-id.yaml"
        - $ref: "parameters/path/id.yaml"
      responses:
        "204":
          description: The subscription was deleted
        "400":
          $ref: "responses/400-subscription-id.yaml"
        "401":
          $ref: "responses/401-unauthenticated.yaml"
        "403":
          $ref: "responses/403-unauthorised.yaml"
        "404":
          $ref: "responses/404-not-found.yaml"
        "500":
          $ref: "responses/500-internal-server-error.yaml"

    put:
      summary: "Edit a subscription"
      tags:
        - subscriptions
      description: |
        ### Overview
        Use this endpoint to edit (update) an existing subscription.
        The update will apply immediately, overwriting the existing subscription with the given id.

        ### Sandbox testing
        You can test the following scenarios in our sandbox environment:

        | Scenario                                  | Request                                                                  | Response                                                                    |
        | ----------------------------------------- | ------------------------------------------------------------------------ | --------------------------------------------------------------------------- |
        | Subscription exists and can be updated    | `id=e9050741-ae87-4720-beb1-2abd9248e227`                                | HTTP Status 204 resource updated response                                   |
        | Subscription does not exist               | `id=236a1d4a-5d69-4fa9-9c7f-e72bf505aa5b` (or any other valid UUID)      | HTTP Status 404 containing problem description                              |
        | Matching subscription already exists      | `id=f8f44c83-a697-4607-8604-a1a45acedd8c`                                | HTTP Status 409 containing problem description                              |
        | Publish a subscription with invalid data  | Modify the subscription to have an invalid value for `resourceType`      | HTTP Status 400 and response containing a validation error.                 |

        You can try out the sandbox using the 'Try this API' feature on this page.
      operationId: update-subscription
      parameters:
        - $ref: "parameters/headers/authorization.yaml"
        - $ref: "parameters/headers/x-correlation-id.yaml"
        - $ref: "parameters/path/id.yaml"
      requestBody:
        $ref: "requestBody/create-or-update-subscription-body.yaml"
      responses:
        "204":
          description: The subscription was updated
        "400":
          $ref: "responses/400-subscription-id.yaml"
        "401":
          $ref: "responses/401-unauthenticated.yaml"
        "403":
          $ref: "responses/403-unauthorised.yaml"
        "409":
          $ref: "responses/409-matching-subscription.yaml"
        "500":
          $ref: "responses/500-internal-server-error.yaml"

components:
  schemas:
    cloudevent:
      $ref: "schemas/cloudevents/mns-publish-cloudevent.yaml"
